# -*- coding: utf-8 -*-
"""day6.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1AzMGImEMNwUOPb2DHKPG88hxsr03Ee7-
"""

# 100 days of python day 6
# hangman game
movies = ["Inception","Titanic","Avatar","Gladiator","Interstellar","Avengers","Frozen","Twilight","Coco","Shrek","Moana","Zootopia"]
import random
name=random.choice(movies).lower()
placeholder=''
for i in range(len(name)):
  placeholder+=' _ '
print(placeholder)
count=4
game_over=False
words=[]
while game_over!= True:
  display=''
  guess=input('Guess the word->')
  if guess in words:
    print(f"You have already guessed the {guess}")
  for i in name:
    if i==guess or i in words:
      display+=i
      words.append(i)
    else:
      display+=' _ '
  if guess not in name:
    count-=1
    print(f'Wrong guess you have {count} lives left')
    if count==0:
      print('Game_over')
      print(f'it was {name} ')
      game_over=True
  if ' _ ' not in display:
    print('Congrats you won it was ')
    game_over=True
  print(display)

