# -*- coding: utf-8 -*-
"""day4.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1AzMGImEMNwUOPb2DHKPG88hxsr03Ee7-
"""

# 100 days of python day 4
# Rock paper scissors
import random
inputs=['rock','paper','scissors']
user_input=input('choose rock,paper,scissors ->').lower()
comp_choice=random.choice(inputs)
if user_input not in inputs:
  print('Invalid')
else:
  if ((user_input=='rock' and comp_choice=='scissors') or
     (user_input=='paper' and comp_choice=='rock') or
     (user_input=='scissors' and comp_choice=='paper')):
     print(f'{user_input} v/s {comp_choice} you won ')
  elif user_input==comp_choice:
     print(f'{user_input} v/s {comp_choice} Draw')
  else:
     print(f'{user_input} v/s {comp_choice} you lost ')

