# -*- coding: utf-8 -*-
"""day1.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1AzMGImEMNwUOPb2DHKPG88hxsr03Ee7-
"""

# I took 100 days challenge this is day 1
# too add top names
first_name=input('Enter the city yiu grew up!\n')
second_name=input('enter your pets name\n')
print(first_name,second_name)