# -*- coding: utf-8 -*-
"""day2.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1AzMGImEMNwUOPb2DHKPG88hxsr03Ee7-
"""

# 100 days of python day 2
# calculating the bill
bill=float(input('Enter the total bill  '))
tip=float(input('Enter the tip in percentage  '))
total_bill= round((1+(tip/100))*bill,2)
persons=int(input('How people are splitting?  '))
per_cost=round(total_bill/persons,2)
print(f'Your final bill per person={per_cost}$')

