# -*- coding: utf-8 -*-
"""day3.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1AzMGImEMNwUOPb2DHKPG88hxsr03Ee7-
"""

# 100 days of python day 3
# Treasure hunt
import time
print('Welcome to Treasure island\nYour mission is to find Treasure')
ready=input('Are you ready Y/N?').lower()
if ready=='y':
  print('Loading.',end='')
  for i in range(6):
    print(' . ',end='')
    time.sleep(1)
  side=input('\nYour arrived at island which way you want go left/right??\n').lower()
  if side=='left':
    boat=input('You see a broken house at the other end of river\nYou want to swin or wait for boat??\nAnswer in swin/boat\n').lower()
    if boat=='boat':
      door=input("Which door you want to choose Red/Yellow/Blue\n").lower()
      if door=='yellow':
        print('Congratulations you won')
      else:
        print('Wrong door game over :(')
    else:
      print('Game over you got eaten by local sharks :(')
  else:
    print('Game over you spent 3 days searching.. wrong way')
else:
  print('Come back when your ready :)')

